In [1]:
import pandas as pd
import numpy as np

In [2]:
data_4_uci = pd.read_csv('Data_for_UCI_named.csv')

In [3]:
data_4_uci.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [4]:
data_4_uci.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   tau1    10000 non-null  float64
 1   tau2    10000 non-null  float64
 2   tau3    10000 non-null  float64
 3   tau4    10000 non-null  float64
 4   p1      10000 non-null  float64
 5   p2      10000 non-null  float64
 6   p3      10000 non-null  float64
 7   p4      10000 non-null  float64
 8   g1      10000 non-null  float64
 9   g2      10000 non-null  float64
 10  g3      10000 non-null  float64
 11  g4      10000 non-null  float64
 12  stab    10000 non-null  float64
 13  stabf   10000 non-null  object 
dtypes: float64(13), object(1)
memory usage: 1.1+ MB


In [5]:
data_4_uci.isna().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64

In [6]:
data_4_uci = data_4_uci.drop(columns='stab')

In [7]:
data_4_uci.head(2)

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   

         p4        g1        g2        g3        g4     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760    stable

In [8]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder


In [9]:
uci_data = pd.get_dummies(data_4_uci, columns = ['stabf'])

In [10]:
uci_data = uci_data.drop(columns='stabf_unstable')
uci_data.head(2)

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   

         p4        g1        g2        g3        g4  stabf_stable  
0 -1.723086  0.650456  0.859578  0.887445  0.958034             0  
1 -1.255012  0.413441  0.862414  0.562139  0.781760             1

In [11]:
uci_data.rename(columns = {'stabf_stable':'stabf'}, inplace = True)

In [12]:
uci_data.head(3)

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   

         p4        g1        g2        g3        g4  stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034      0  
1 -1.255012  0.413441  0.862414  0.562139  0.781760      1  
2 -0.920492  0.163041  0.766689  0.839444  0.109853      0

In [13]:
scaler = StandardScaler()
scaler.fit(uci_data.drop('stabf',axis=1))

StandardScaler()

In [14]:
scaled_features = scaler.transform(uci_data.drop('stabf',axis=1))
uci_feat = pd.DataFrame(scaled_features,columns=uci_data.columns.drop('stabf'))
uci_feat.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0 -0.835374 -0.791317  1.141704  1.652103  0.017397  1.079405 -0.017078   
1  1.478297 -0.126705 -0.803111 -1.415043  1.752124 -1.593619 -1.438158   
2  1.357093  1.312140 -0.803499 -1.471504 -0.458492  0.098253 -0.062840   
3 -1.653138  0.882289 -0.278354 -1.060901  0.284250  0.513904 -1.591046   
4 -0.771543  0.860108 -0.111670  1.680114 -0.298075  0.287450 -1.376343   

         p4        g1        g2        g3        g4  
0 -1.092545  0.457467  1.220013  1.321628  1.579026  
1 -0.011575 -0.406791  1.230354  0.135424  0.936256  
2  0.760963 -1.319852  0.881299  1.146596 -1.513802  
3  0.583414 -0.287304  1.647250  1.474543 -0.591750  
4  1.606636  0.992226 -0.253610  0.481133  1.079063

In [15]:
X = uci_feat
y = uci_data['stabf']

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
y_train.value_counts()

0    5092
1    2908
Name: stabf, dtype: int64

In [18]:
import imblearn
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state= 1 )
x_train_sm, y_train_sm = smote.fit_resample(x_train, y_train) 

In [19]:
y_train_sm.shape

x_train_sm.shape



(10184, 12)

## Decision Tree

In [20]:
from sklearn.tree import DecisionTreeClassifier

In [21]:
d_tree = DecisionTreeClassifier()

In [22]:
d_tree.fit(x_train_sm,y_train_sm)

DecisionTreeClassifier()

In [23]:
d_predict = d_tree.predict(x_test)

In [24]:
from sklearn.metrics import confusion_matrix, classification_report

In [25]:
print(confusion_matrix(y_test,d_predict))
print('\n')
print(classification_report(y_test,d_predict))

[[1116  172]
 [ 133  579]]


              precision    recall  f1-score   support

           0       0.89      0.87      0.88      1288
           1       0.77      0.81      0.79       712

    accuracy                           0.85      2000
   macro avg       0.83      0.84      0.84      2000
weighted avg       0.85      0.85      0.85      2000



## Random Forest

In [26]:
from sklearn.ensemble import RandomForestClassifier

In [27]:
regressor = RandomForestClassifier(n_estimators = 100, random_state = 1)

In [28]:
regressor.fit(x_train_sm,y_train_sm)

RandomForestClassifier(random_state=1)

In [29]:
rfc_pred = regressor.predict(x_test)

In [30]:
print(confusion_matrix(y_test,rfc_pred))
print('\n')
print(classification_report(y_test,rfc_pred))

[[1191   97]
 [  68  644]]


              precision    recall  f1-score   support

           0       0.95      0.92      0.94      1288
           1       0.87      0.90      0.89       712

    accuracy                           0.92      2000
   macro avg       0.91      0.91      0.91      2000
weighted avg       0.92      0.92      0.92      2000



## Lightgbm

In [31]:
import lightgbm as lgb

In [32]:
from lightgbm import LGBMClassifier

In [33]:
model = LGBMClassifier(random_state=1)

In [34]:
model.fit(x_train, y_train)

LGBMClassifier(random_state=1)

In [35]:
pred = model.predict(x_test)

In [36]:
print(confusion_matrix(y_test,pred))
print('\n')
print(classification_report(y_test,pred))

[[1236   52]
 [  68  644]]


              precision    recall  f1-score   support

           0       0.95      0.96      0.95      1288
           1       0.93      0.90      0.91       712

    accuracy                           0.94      2000
   macro avg       0.94      0.93      0.93      2000
weighted avg       0.94      0.94      0.94      2000



## Extra tree classifier

In [37]:
from sklearn.ensemble import ExtraTreesClassifier 

In [38]:
extra_tree_forest = ExtraTreesClassifier(n_estimators  = 5, n_jobs = -1,verbose = 1,random_state = 1) 

In [39]:
extra_tree_forest.fit(x_train_sm, y_train_sm) 

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    0.0s finished


ExtraTreesClassifier(n_estimators=5, n_jobs=-1, random_state=1, verbose=1)

In [40]:
extra_pred = extra_tree_forest.predict(x_test)

[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   5 out of   5 | elapsed:    0.0s finished


In [41]:
print(confusion_matrix(y_test,extra_pred))
print('\n')
print(classification_report(y_test,extra_pred))

[[1115  173]
 [ 166  546]]


              precision    recall  f1-score   support

           0       0.87      0.87      0.87      1288
           1       0.76      0.77      0.76       712

    accuracy                           0.83      2000
   macro avg       0.81      0.82      0.82      2000
weighted avg       0.83      0.83      0.83      2000

